from distutils.dir_util import copy_tree
import os

#Open the file list generated by get_paths.py
filename = open("path_frac.log","r+")

#Base Destination Directory
base_path = "/home/youy/Documents/Spine/batch_test2/"

#Go through each file path and copy to destination
for path in filename:
    study_id = path.split("/")[-1]
    
    if os.path.exists(os.path.join(base_path,study_id)) == False:
        os.mkdir(os.path.join(base_path,study_id)
    
    Dest = os.path.join(base_path,study_id)
    copy_tree(Source,Dest)
    
